# In[0]: Imports
import json
import yaml
from pathlib import Path
from .utils.utils import log

# In[1]: WGS Pipeline
def run_wgs_pipeline(
        console=False,
        config=None,
        **args
):
    # Step 1: Read the config file
    if not config:
        raise log(console, f"Config file is required for running the WGS pipeline.", style="danger")
    
    try:
        with open(config, 'r') as f:
            config_data = yaml.safe_load(f)
    except Exception as e:
        raise log(console, f"Failed to read the config file: {e}", style="danger")

    # Step 2: check that all required config sections are present, and check all files that are not generated by the pipeline exist
    # TODO: 

    # Step 2: if index creation is disabled, check that all samples have indexes
    if config_data['index'].get("run") == False:
        # log(console, "Not creating index for samples... ensuring index exists", style="warning")
        try:   
            from .utils.utils import check_index
            check_index(config_data, console)

        except Exception as e:
            log(console, f"Failed to check index: {e}", style="danger")

    # Step 3: if index creation is enabled, create indexes for all samples
    if config_data['index'].get('run') == True:
        # log(console, "Creating index for all samples...", style="info")   
        try:
            from .utils.utils import create_index
            create_index(config_data, console)

        except Exception as e:
            log(console, f"Failed to create index: {e}", style="danger")

    # Step 4: if read counting is enabled, count reads for all samples
    if config_data['count_reads'].get('run') == True:
        # log(console, "Counting reads for all samples...", style="info")
        try: 
            from .utils.count_reads import count_reads
            count_reads(config_data, console)
        except Exception as e:
            log(console, f"Failed to count reads: {e}", style="danger")

    # Step 5: if mosdepth is enabled, calculate mosdepth for all samples
    if config_data['mosdepth'].get('run') == True:
        # log(console, "Calculating mosdepth for all samples...", style="info")
        try:
            from .utils.mosdepth import compute_mosdepth
            compute_mosdepth(config_data, console)
        except Exception as e:
            log(console, f"Failed to calculate mosdepth: {e}", style="danger")

    # Step 6: if normalization is enabled, normalize coverage for all samples
    if config_data['mosdepth']['normalize'].get('run') == True:
        # log(console, "Normalizing coverage for all samples...", style="info")
        try:
            from .utils.normalize_mosdepth import normalize_mosdepth
            normalize_mosdepth(config_data, console)
        except Exception as e:
            log(console, f"Failed to normalize coverage: {e}", style="danger")

    # Step 7: find neighbors from normalized coverage for all samples
    if config_data['mosdepth']['neighbors'].get('run') == True:
        # log(console, "Finding neighbors for all samples...", style="info")
        try:
            from .utils.find_neighbors import find_neighbors
            find_neighbors(config_data, console)
        except Exception as e:
            log(console, f"Failed to find neighbors: {e}", style="danger")

    # Step 8: compute diploid cnv calls for all samples
    if config_data['compute_diploid_genotypes'].get('run') == True:
        # log(console, "Computing diploid CNV calls for all samples...", style="info")
        try:
            from .utils.compute_dipcn import compute_diploid_genotypes
            compute_diploid_genotypes(config_data, console)
        except Exception as e:
            log(console, f"Failed to compute diploid CNV calls: {e}", style="danger")
    # Step 9: compute haploid cnv calls for all samples 
    pass

# In[2]: WES Pipeline
def run_wes_pipeline(
        console=False,
        config=None,
        **args
):
    pass