name: Build and Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install mamba
      - name: Install dependencies
        run: |
          conda install mamba -n base -c conda-forge
          mamba env update -n docs -f docs/environment.yml


      # Build the site
      - name: Build Docs
        run: |
          cd docs
          make html  # or sphinx-build -b html source build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
