name: Build and Deploy Website

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Conda
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.12
          auto-update-conda: true
          environment-file: docs/environment.yml
          activate-environment: docs

      - name: Verify Conda Environment
        run: conda info --envs && conda list
        
      # - name: Install Dependencies
      #   run: |
      #     conda activate docs
      #     pip install -r docs/environment.yml

      - name: Build Docs
        shell: bash
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          publish_branch: gh-pages
