name: Build and Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true

      - name: Install dependencies
        shell: bash
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda install -n base -c conda-forge mamba
          mamba env create -n docs -f docs/environment.yml || \
          mamba env update -n docs -f docs/environment.yml
          conda activate docs

      - name: Build Docs
        shell: bash
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
